name: replearn
channels:
  - defaults
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - jupyterlab
  - ipywidgets
  - pip:
      - pm4py
      - tqdm
      - fastcluster
      - tensorflow
      - gensim
      - nltk